# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1415db5298d20f416374a22ca420b5e61e01f475de331c7c59a79d1f3207f012c4693d578b91abb6270956217609fba74e5120eb7ab6ea5589542e4c82fbb9f7

test:
  secret_key_base: 35b619cc9485f1747448c3c8a98e5b3b7c4e189506e7e4f2751d036bcff469fc95a964ff531a34d3f87c35bfcb10e3bf380dda68ffa300c6aa29d5d1055910ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
